### ISSUE TITLE
code_scanning.write_repo_cs_list type error

### ISSUE THREAD

**Issue by sandeepeat2014** [advanced-security/ghas-to-csv#47]
Getting following error:

Run advanced-security/ghas-to-csv@v3
/usr/bin/docker run --name a6c8ceb[4](https://github.com/Eaton-Sandbox/BLDCSM-FOR-STARFISH-GATEWAY/actions/runs/5461369678/jobs/9939299754#step:3:5)a[5](https://github.com/Eaton-Sandbox/BLDCSM-FOR-STARFISH-GATEWAY/actions/runs/5461369678/jobs/9939299754#step:3:6)53734254b1ba81711b[6](https://github.com/Eaton-Sandbox/BLDCSM-FOR-STARFISH-GATEWAY/actions/runs/5461369678/jobs/9939299754#step:3:7)2[7](https://github.com/Eaton-Sandbox/BLDCSM-FOR-STARFISH-GATEWAY/actions/runs/5461369678/jobs/9939299754#step:3:8)d01061_71b2c3 --label 2a6c[8](https://github.com/Eaton-Sandbox/BLDCSM-FOR-STARFISH-GATEWAY/actions/runs/5461369678/jobs/9939299754#step:3:9)c --workdir /github/workspace --rm -e "GITHUB_PAT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIR...
Traceback (most recent call last):
Starting GitHub security report...
  File "/app/main.py", line 12[9](https://github.com/Eaton-Sandbox/BLDCSM-FOR-STARFISH-GATEWAY/actions/runs/5461369678/jobs/9939299754#step:3:10), in <module>
    code_scanning.write_repo_cs_list(cs_list)
  File "/app/src/code_scanning.py", line 87, in write_repo_cs_list
    if cs["state"] == "open":
       ~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by jpnovais** [comment]
Same here :(

**Comment by ctcampbell** [comment]
Is this issue still occurring for any commenters?
