### ISSUE TITLE
Feature Request - Add Repo-> Team/Topic/Custom-Properties column

### ISSUE THREAD

**Issue by felickz** [advanced-security/ghas-to-csv#61]
Additional columns to support reporting scenarios
 -  teams that map to the repo
 - repo topic
 - repo properties

**Comment by bahag-gabelm** [comment]
Hi there, we are also really interested in this feature request, as we use this exported data for our reporting. We would really need to have the topics exported to the CSV files as well. Thanks!

**Comment by aegilops** [comment]
Adding this is desirable, but would require many API calls when used at the org or Enterprise level.

We can consider adding it gated by a flag, so that default users aren't exposed to very long query times.

I may get to this myself, but please feel free to raise a PR if it's important to you.
