### ISSUE TITLE
TypeError: string

### ISSUE THREAD

**Issue by KirtiMenon95** [advanced-security/ghas-to-csv#64]
### Discussed in https://github.com/advanced-security/ghas-to-csv/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **KirtiMenon95** March 13, 2024</sup>
Hi, 

I am trying to use this action by writing below workflow 
name: GitHub Advanced Security API to CSV

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run GitHub Advanced Security API to CSV action
        uses: advanced-security/ghas-to-csv@v3
        env:
          GITHUB_PAT: ${{ secrets.GHAS }}
        
      - name: Upload CSV
        uses: actions/upload-artifact@v3
        with:
          name: ghas-data
          path: ${{ github.workspace }}/*.csv
          if-no-files-found: error

when running the action I see error
Traceback (most recent call last):
  File "/app/main.py", line 129, in <module>
Starting GitHub security report...
    code_scanning.write_repo_cs_list(cs_list)
  File "/app/src/code_scanning.py", line 87, in write_repo_cs_list
    if cs["state"] == "open":
       ~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

Please help me get this sorted.</div>

**Comment by zkoppert** [comment]
I'm running into this problem too but curiously, this code that is causing the problem is no longer on the main branch. I believe this issue could be fixed, but no release has occurred so we aren't getting the latest code when we refer to the v3 tag.

@aegilops Could you cut a new release to help resolve this issue?

**Comment by aegilops** [comment]
I re-released v3 with the latest changes, so that may address things: https://github.com/advanced-security/ghas-to-csv/releases/tag/v3

Please let me know if the problem persists, and I'll see what's up

**Comment by zkoppert** [comment]
Tried it out just now, and its working for me. Thank you!

**Comment by bard-hobson** [comment]
Worked for me as well. Great work!

**Comment by zkoppert** [comment]
@KirtiMenon95 or anyone else please reopen this issue if you see it come up again.

**Comment by KirtiMenon95** [comment]
Thanks team, I used the script to modify for my requirement and fixed the bug. :)
